debug for list the directories

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,7 +40,17 @@ jobs:
 
     - name: Build
       run: dotnet build Respify/Respify.csproj --no-restore --configuration Release
-
+      
+    - name: Verify test DLL exists
+      run: |
+        if [ ! -f Respify.Tests/bin/Release/net8.0/Respify.Tests.dll ]; then
+          echo "Test DLL not found."
+          exit 1
+        fi
+        
+    - name : list test output directory
+      run: ls -la Respify.Tests/bin/Release/net8.0
+      
     - name: Run tests
       run: dotnet test Respify.Tests/Respify.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"
 
